syntax = "proto3";

package game;

// Level definition
message Level {
    string name = 1;
    string version = 2;
    string description = 3;
    Background background = 4;
    LevelScript level_script = 5;
    repeated MobBatch mob_batches = 6;
    repeated Mob mobs = 7;
    repeated Attack attacks = 8;
    repeated Boss bosses = 9;
    repeated Bullet bullets = 10;
}

// Background definition
message Background {
    string model_3d = 1; // .glb file
    repeated ShaderPair shaders = 2; // pairs of shader files (.frag, .vert)
    string background_script = 3; // .cpp file (like Unity MonoBehaviour)
}

// Shader pair definition
message ShaderPair {
    string fragment_shader = 1; // .frag file
    string vertex_shader = 2; // .vert file
}

// Level script definition
message LevelScript {
    string script = 1; // .cpp file (like Unity MonoBehaviour)
}

// Mob batch definition
message MobBatch {
    string mob_batch_id = 1;
    repeated string mob_ids = 2; // ids of mobs in this batch
    float delay_after_previous_batch = 3; // delay after previous batch
    float lifespan = 4; // on timer end prepare next batch
}

// Mob definition
message Mob {
    string mob_id = 1;
    float health = 2;
    string sprite = 3; // .png or .jpg file
    float spawn_delay = 4; // relative to batch spawn begin
    Path path = 5;
    Drop drop = 6;
    string attack_id = 7;
    Collider collider = 8;
}

// Path definition
message Path {
    repeated Point key_points = 1; // points on the player's screen
    float travel_time = 2; // in seconds
}

// Point definition
message Point {
    float x = 1;
    float y = 2;
}

// Drop definition
message Drop {
    string item = 1; // large P, P, points, etc.
    float drop_weight = 2; // unsigned float != 0
}

// Attack definition
message Attack {
    string attack_id = 1;
    string bullet_id = 2;
}

// Boss definition
message Boss {
    string boss_id = 1;
    bool finally = 2; // if final boss
    string batch_id = 3; // batch to spawn after
    string drop_item = 4; // bombs or 1UPs
    Collider collider = 5;
    repeated Phase phases = 6;
}

// Phase definition
message Phase {
    repeated Attack attacks = 1;
    float health = 2;
    string spell_card_id = 3; // nullable
}

// Spell card definition
message SpellCard {
    string spell_card_id = 1;
    string name = 2;
    float damage_reduction = 3; // coefficient
    ShaderPair background = 4;
}

// Bullet definition
message Bullet {
    string bullet_id = 1; // prefab id
    float damage = 2;
    Collider collider = 3;
}

// Collider definition
message Collider {
    float offset_x = 1;
    float offset_y = 2;
    oneof collider_type {
        CircleCollider circle_collider = 3;
        RectangleCollider rectangle_collider = 4;
    }
}

// Circle collider definition
message CircleCollider {
    float radius = 1;
}

// Rectangle collider definition
message RectangleCollider {
    float width = 1;
    float height = 2;
}
