syntax = "proto3";

package game;

message Vector2 {
    float x = 1;
    float y = 2;
}

message Collider {
    Vector2 offset = 1;
    oneof collider_type {
        CircleCollider circle = 2;
        RectangleCollider rectangle = 3;
    }

    message CircleCollider {
        float radius = 1;
    }

    message RectangleCollider {
        float angle = 1;
        float width = 2;
        float height = 3;
    }
}

message RandomConfig {
    float min_value = 1;
    float max_value = 2;
}

message Bullet {
    float damage = 1;
    string sprite = 2;
    Collider collider = 3;
    optional BulletLifeConfig bullet_life_config = 4;

    message BulletLifeConfig {
        float lifespan = 1;
        optional uint32 attack_id = 2;
    }
}

message Attack {
    string name = 1;
    oneof attack_type {
        uint32 bullet_id = 2;
        uint32 attack_id = 3;
    }
    float speed = 4;
    Vector2 spawn_position_offset = 5;
    float amount = 6;

    oneof attack_pattern {
        CircleAttack circle = 7;
        ArcAttack arc = 8;
        LineAttack line = 9;
        SpiralAttack spiral = 10;
    }

    message CircleAttack {
        float rotation_angle = 1;
    }

    message ArcAttack {
        bool lock_on_player = 1;
        float direction_angle = 2;
        float spread_angle = 3;
    }

    message LineAttack {
        bool lock_on_player = 1;
        float direction_angle = 2;
        float delta_time = 3;
        oneof speed_config {
            float delta_speed = 4;
            RandomConfig random_speed = 5;
        }
        oneof amount_config {
            float delta_amount = 6;
            RandomConfig random_amount = 7;
        }
        oneof direction_config {
            float delta_direction = 8;
            RandomConfig random_direction = 9;
        }
    }

    message SpiralAttack {
        bool lock_on_player = 1;
        float begin_angle = 2;
        float rotation_angle = 3;
        float delta_time = 4;
        oneof speed_config {
            float delta_speed = 5;
            RandomConfig random_speed = 6;
        }
        oneof amount_config {
            float delta_amount = 7;
            RandomConfig random_amount = 8;
        }
        oneof direction_config {
            float delta_direction = 9;
            RandomConfig random_direction = 10;
        }
    }
}

message DropItem {
    string item = 1;
    double weight = 2;
    bool fixed_amount = 3;
    oneof amount {
        uint32 fixed = 4;
        RangeAmount range = 5;
    }

    message RangeAmount {
        uint32 min = 1;
        uint32 max = 2;
    }
}

message MobPrefab {
    string name = 1;
    double health = 2;
    string sprite = 3;
    DropItem drop_item = 4;
    uint32 attack_id = 5;
    Collider collider = 6;
}

message Path {
    repeated Vector2 key_points = 1;
    float travel_time = 2;
    oneof spline_type {
        BSpline b_spline = 3;
        CardinalSpline cardinal_spline = 4;
    };
    bool const_speed = 5;

    message BSpline {}

    message CardinalSpline {
        float s = 1;
    }
}

message Mob {
    string name = 1;
    uint32 mob_prefab_id = 2;
    float spawn_delay = 3;
    Path path = 4;
    optional DropItem drop_item = 5;
}

message MobBatch {
    string name = 1;
    repeated Mob mobs = 2;
    float delay_after_previous_batch = 3;
    float lifespan = 4;
}

message SpellCard {
    uint32 spell_card_id = 1;
    string name = 2;
    float damage_reduction = 3;
    message Background {
        repeated ShaderPair shaders = 1;
    }
    Background bg = 4;
}

message BossPhase {
    message PhaseAttack {
        uint32 attack_id = 1;
        float health = 2;
        optional uint32 spell_card_id = 3;
    }
    repeated PhaseAttack attacks = 1;
    repeated SpellCard spell_cards = 2;
}

message Boss {
    string name = 1;
    bool finally = 2;
    uint32 batch_id = 3;
    DropItem drop_item = 4;
    Collider collider = 5;
    repeated BossPhase phases = 6;
}

message ShaderPair {
    string fragment_shader = 1; // .frag file
    string vertex_shader = 2; // .vert file
}

message Background {
    string model_3d = 1; // .glb file
    repeated ShaderPair shaders = 2; // pairs of shader files (.frag, .vert)
    string bg_script = 3; // .cpp file
}

message Level {
    string name = 1;
    string version = 2;
    string description = 3;
    Background bg = 4;
    string level_script = 5;
    repeated MobBatch mob_batches = 6;
    repeated MobPrefab mob_prefabs = 7;
    repeated Attack attacks = 8;
    repeated Bullet bullets = 9;
    repeated Boss bosses = 10;
}
