#include "levelgenerator.h"

#include "editor/game.pb.h"

#include <google/protobuf/util/time_util.h>

#include <fstream>
#include <iostream>

using namespace game;

// NOLINTBEGIN
void qGenerateTestLevel(std::string filepath)
{
    using namespace game;
    using google::protobuf::util::TimeUtil;
    Level level;

    // Basic level info
    level.set_name("Example Level");
    level.set_version("1.0");
    level.set_description("This is an example level generated by the function");

    // Background
    auto *bg = level.mutable_bg();
    bg->set_model_3d("background.glb");
    bg->set_bg_script("background.cpp");

    // Add shaders (3 items)
    auto *shader1 = bg->add_shaders();
    shader1->set_fragment_shader("shader1.frag");
    shader1->set_vertex_shader("shader1.vert");

    auto *shader2 = bg->add_shaders();
    shader2->set_fragment_shader("shader2.frag");
    shader2->set_vertex_shader("shader2.vert");

    auto *shader3 = bg->add_shaders();
    shader3->set_fragment_shader("shader3.frag");
    shader3->set_vertex_shader("shader3.vert");

    level.set_level_script("level_script.cpp");

    // Bullets (3 items)
    auto *bullet1 = level.add_bullets();
    bullet1->set_damage(10);
    bullet1->set_sprite("bullet1.png");
    auto *bullet1_collider = bullet1->mutable_collider();
    bullet1_collider->mutable_offset()->set_x(0);
    bullet1_collider->mutable_offset()->set_y(0);
    auto *bullet1_circle = bullet1_collider->mutable_circle();
    bullet1_circle->set_radius(5);
    auto *bullet1_life = bullet1->mutable_bullet_life_config();
    bullet1_life->set_lifespan(3.0);
    bullet1_life->set_attack_id(1);

    auto *bullet2 = level.add_bullets();
    bullet2->set_damage(20);
    bullet2->set_sprite("bullet2.png");
    auto *bullet2_collider = bullet2->mutable_collider();
    bullet2_collider->mutable_offset()->set_x(0);
    bullet2_collider->mutable_offset()->set_y(0);
    auto *bullet2_rect = bullet2_collider->mutable_rectangle();
    bullet2_rect->set_angle(0);
    bullet2_rect->set_width(10);
    bullet2_rect->set_height(5);

    auto *bullet3 = level.add_bullets();
    bullet3->set_damage(15);
    bullet3->set_sprite("bullet3.png");
    auto *bullet3_collider = bullet3->mutable_collider();
    bullet3_collider->mutable_offset()->set_x(5);
    bullet3_collider->mutable_offset()->set_y(5);
    auto *bullet3_circle = bullet3_collider->mutable_circle();
    bullet3_circle->set_radius(8);

    // Attacks (3 items)
    auto *attack1 = level.add_attacks();
    attack1->set_name("Circle Attack");
    attack1->set_bullet_id(1);
    attack1->set_speed(100);
    attack1->mutable_spawn_position_offset()->set_x(0);
    attack1->mutable_spawn_position_offset()->set_y(0);
    attack1->set_amount(12);
    auto *circle_attack = attack1->mutable_circle();
    circle_attack->set_rotation_angle(30);

    auto *attack2 = level.add_attacks();
    attack2->set_name("Arc Attack");
    attack2->set_bullet_id(2);
    attack2->set_speed(150);
    attack2->mutable_spawn_position_offset()->set_x(10);
    attack2->mutable_spawn_position_offset()->set_y(0);
    attack2->set_amount(8);
    auto *arc_attack = attack2->mutable_arc();
    arc_attack->set_lock_on_player(true);
    arc_attack->set_direction_angle(45);
    arc_attack->set_spread_angle(90);

    auto *attack3 = level.add_attacks();
    attack3->set_name("Spiral Attack");
    attack3->set_bullet_id(3);
    attack3->set_speed(200);
    attack3->mutable_spawn_position_offset()->set_x(0);
    attack3->mutable_spawn_position_offset()->set_y(10);
    attack3->set_amount(24);
    auto *spiral_attack = attack3->mutable_spiral();
    spiral_attack->set_lock_on_player(true);
    spiral_attack->set_begin_angle(0);
    spiral_attack->set_rotation_angle(15);
    spiral_attack->set_delta_time(0.1);
    spiral_attack->set_delta_speed(5);
    spiral_attack->set_delta_amount(1);
    spiral_attack->set_delta_direction(5);

    // MobPrefabs (3 items)
    auto *mob_prefab1 = level.add_mob_prefabs();
    mob_prefab1->set_name("Small Enemy");
    mob_prefab1->set_health(50);
    mob_prefab1->set_sprite("small_enemy.png");
    mob_prefab1->mutable_drop_item()->set_item("coin");
    mob_prefab1->mutable_drop_item()->set_weight(0.8);
    mob_prefab1->mutable_drop_item()->set_fixed_amount(true);
    mob_prefab1->mutable_drop_item()->set_fixed(1);
    mob_prefab1->set_attack_id(1);
    auto *mob_prefab1_collider = mob_prefab1->mutable_collider();
    mob_prefab1_collider->mutable_offset()->set_x(0);
    mob_prefab1_collider->mutable_offset()->set_y(0);
    auto *mob_prefab1_circle = mob_prefab1_collider->mutable_circle();
    mob_prefab1_circle->set_radius(10);

    auto *mob_prefab2 = level.add_mob_prefabs();
    mob_prefab2->set_name("Medium Enemy");
    mob_prefab2->set_health(100);
    mob_prefab2->set_sprite("medium_enemy.png");
    mob_prefab2->mutable_drop_item()->set_item("gem");
    mob_prefab2->mutable_drop_item()->set_weight(0.5);
    mob_prefab2->mutable_drop_item()->set_fixed_amount(false);
    auto *range_amount = mob_prefab2->mutable_drop_item()->mutable_range();
    range_amount->set_min(1);
    range_amount->set_max(3);
    mob_prefab2->set_attack_id(2);
    auto *mob_prefab2_collider = mob_prefab2->mutable_collider();
    mob_prefab2_collider->mutable_offset()->set_x(0);
    mob_prefab2_collider->mutable_offset()->set_y(0);
    auto *mob_prefab2_rect = mob_prefab2_collider->mutable_rectangle();
    mob_prefab2_rect->set_angle(0);
    mob_prefab2_rect->set_width(20);
    mob_prefab2_rect->set_height(15);

    auto *mob_prefab3 = level.add_mob_prefabs();
    mob_prefab3->set_name("Large Enemy");
    mob_prefab3->set_health(200);
    mob_prefab3->set_sprite("large_enemy.png");
    mob_prefab3->mutable_drop_item()->set_item("power_up");
    mob_prefab3->mutable_drop_item()->set_weight(0.3);
    mob_prefab3->mutable_drop_item()->set_fixed_amount(true);
    mob_prefab3->mutable_drop_item()->set_fixed(1);
    mob_prefab3->set_attack_id(3);
    auto *mob_prefab3_collider = mob_prefab3->mutable_collider();
    mob_prefab3_collider->mutable_offset()->set_x(0);
    mob_prefab3_collider->mutable_offset()->set_y(0);
    auto *mob_prefab3_circle = mob_prefab3_collider->mutable_circle();
    mob_prefab3_circle->set_radius(25);

    // MobBatches (3 items)
    auto *mob_batch1 = level.add_mob_batches();
    mob_batch1->set_name("First Wave");
    mob_batch1->set_delay_after_previous_batch(0);
    mob_batch1->set_lifespan(30);

    // Add mobs to first batch (3 items)
    auto *mob1 = mob_batch1->add_mobs();
    mob1->set_name("Small Mob 1");
    mob1->set_mob_prefab_id(1);
    mob1->set_spawn_delay(0);
    auto *mob1_path = mob1->mutable_path();
    mob1_path->set_travel_time(10);
    mob1_path->set_const_speed(true);
    mob1_path->mutable_b_spline();

    // Add key points to path (3 items)
    auto *point1 = mob1_path->add_key_points();
    point1->set_x(0);
    point1->set_y(0);
    auto *point2 = mob1_path->add_key_points();
    point2->set_x(100);
    point2->set_y(100);
    auto *point3 = mob1_path->add_key_points();
    point3->set_x(200);
    point3->set_y(0);

    auto *mob2 = mob_batch1->add_mobs();
    mob2->set_name("Small Mob 2");
    mob2->set_mob_prefab_id(1);
    mob2->set_spawn_delay(1);
    auto *mob2_path = mob2->mutable_path();
    mob2_path->set_travel_time(12);
    mob2_path->set_const_speed(false);
    auto *cardinal = mob2_path->mutable_cardinal_spline();
    cardinal->set_s(0.5);

    // Add key points to path (3 items)
    auto *point4 = mob2_path->add_key_points();
    point4->set_x(0);
    point4->set_y(100);
    auto *point5 = mob2_path->add_key_points();
    point5->set_x(100);
    point5->set_y(0);
    auto *point6 = mob2_path->add_key_points();
    point6->set_x(200);
    point6->set_y(100);

    auto *mob3 = mob_batch1->add_mobs();
    mob3->set_name("Small Mob 3");
    mob3->set_mob_prefab_id(1);
    mob3->set_spawn_delay(2);
    auto *mob3_path = mob3->mutable_path();
    mob3_path->set_travel_time(15);
    mob3_path->set_const_speed(true);
    mob3_path->mutable_b_spline();

    // Add key points to path (3 items)
    auto *point7 = mob3_path->add_key_points();
    point7->set_x(0);
    point7->set_y(50);
    auto *point8 = mob3_path->add_key_points();
    point8->set_x(150);
    point8->set_y(150);
    auto *point9 = mob3_path->add_key_points();
    point9->set_x(300);
    point9->set_y(50);

    // Second batch
    auto *mob_batch2 = level.add_mob_batches();
    mob_batch2->set_name("Second Wave");
    mob_batch2->set_delay_after_previous_batch(5);
    mob_batch2->set_lifespan(40);

    // Add mobs to second batch (3 items)
    auto *mob4 = mob_batch2->add_mobs();
    mob4->set_name("Medium Mob 1");
    mob4->set_mob_prefab_id(2);
    mob4->set_spawn_delay(0);

    auto *mob5 = mob_batch2->add_mobs();
    mob5->set_name("Medium Mob 2");
    mob5->set_mob_prefab_id(2);
    mob5->set_spawn_delay(2);

    auto *mob6 = mob_batch2->add_mobs();
    mob6->set_name("Medium Mob 3");
    mob6->set_mob_prefab_id(2);
    mob6->set_spawn_delay(4);

    // Third batch
    auto *mob_batch3 = level.add_mob_batches();
    mob_batch3->set_name("Third Wave");
    mob_batch3->set_delay_after_previous_batch(10);
    mob_batch3->set_lifespan(50);

    // Add mobs to third batch (3 items)
    auto *mob7 = mob_batch3->add_mobs();
    mob7->set_name("Large Mob 1");
    mob7->set_mob_prefab_id(3);
    mob7->set_spawn_delay(0);

    auto *mob8 = mob_batch3->add_mobs();
    mob8->set_name("Large Mob 2");
    mob8->set_mob_prefab_id(3);
    mob8->set_spawn_delay(3);

    auto *mob9 = mob_batch3->add_mobs();
    mob9->set_name("Large Mob 3");
    mob9->set_mob_prefab_id(3);
    mob9->set_spawn_delay(6);

    // Bosses (3 items)
    auto *boss1 = level.add_bosses();
    boss1->set_name("First Boss");
    boss1->set_finally(false);
    boss1->set_batch_id(1);
    boss1->mutable_drop_item()->set_item("boss_key");
    boss1->mutable_drop_item()->set_weight(1.0);
    boss1->mutable_drop_item()->set_fixed_amount(true);
    boss1->mutable_drop_item()->set_fixed(1);
    auto *boss1_collider = boss1->mutable_collider();
    boss1_collider->mutable_offset()->set_x(0);
    boss1_collider->mutable_offset()->set_y(0);
    auto *boss1_circle = boss1_collider->mutable_circle();
    boss1_circle->set_radius(30);

    // Boss phases (3 items)
    auto *phase1 = boss1->add_phases();
    auto *phase1_attack1 = phase1->add_attacks();
    phase1_attack1->set_attack_id(1);
    phase1_attack1->set_health(0.8);

    auto *phase1_attack2 = phase1->add_attacks();
    phase1_attack2->set_attack_id(2);
    phase1_attack2->set_health(0.5);

    auto *phase1_attack3 = phase1->add_attacks();
    phase1_attack3->set_attack_id(3);
    phase1_attack3->set_health(0.2);

    auto *phase2 = boss1->add_phases();
    auto *phase2_attack1 = phase2->add_attacks();
    phase2_attack1->set_attack_id(2);
    phase2_attack1->set_health(0.7);

    auto *phase3 = boss1->add_phases();
    auto *phase3_attack1 = phase3->add_attacks();
    phase3_attack1->set_attack_id(3);
    phase3_attack1->set_health(0.3);

    // Spell cards for boss (3 items)
    auto *spell_card1 = phase1->add_spell_cards();
    spell_card1->set_spell_card_id(1);
    spell_card1->set_name("First Spell");
    spell_card1->set_damage_reduction(0.5);
    auto *spell_card1_bg = spell_card1->mutable_bg();
    auto *spell_shader1 = spell_card1_bg->add_shaders();
    spell_shader1->set_fragment_shader("spell1.frag");
    spell_shader1->set_vertex_shader("spell1.vert");

    auto *spell_card2 = phase2->add_spell_cards();
    spell_card2->set_spell_card_id(2);
    spell_card2->set_name("Second Spell");
    spell_card2->set_damage_reduction(0.3);

    auto *spell_card3 = phase3->add_spell_cards();
    spell_card3->set_spell_card_id(3);
    spell_card3->set_name("Final Spell");
    spell_card3->set_damage_reduction(0.7);

    // Second boss
    auto *boss2 = level.add_bosses();
    boss2->set_name("Second Boss");
    boss2->set_finally(false);
    boss2->set_batch_id(2);

    // Third boss
    auto *boss3 = level.add_bosses();
    boss3->set_name("Final Boss");
    boss3->set_finally(true);
    boss3->set_batch_id(3);

    std::ofstream output_file(filepath);
    level.SerializeToOstream(&output_file);
    output_file.close();

    // Выводим результат
    std::cout << "Test Level created successfully!" << std::endl;
}
// NOLINTEND
